"""Add MAE/MFE price fields

Revision ID: 6332a76a91ba
Revises: 7ca2a38e51a9
Create Date: 2025-08-09 23:58:48.027739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6332a76a91ba'
down_revision = '7ca2a38e51a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add new columns first
    with op.batch_alter_table('backtest_trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mae_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('mfe_price', sa.Float(), nullable=True))

    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mae_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('mfe_price', sa.Float(), nullable=True))
    
    # Drop old columns
    with op.batch_alter_table('backtest_trade', schema=None) as batch_op:
        batch_op.drop_column('mfe_ticks')
        batch_op.drop_column('mae_ticks')

    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.drop_column('mfe')
        batch_op.drop_column('mae')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mae', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('mfe', sa.FLOAT(), nullable=True))
        batch_op.drop_column('mfe_price')
        batch_op.drop_column('mae_price')

    with op.batch_alter_table('backtest_trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mae_ticks', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('mfe_ticks', sa.FLOAT(), nullable=True))
        batch_op.drop_column('mfe_price')
        batch_op.drop_column('mae_price')

    # ### end Alembic commands ###
