"""Add GlobalImage model

Revision ID: 754c21b10d05
Revises: 480c1f93edf6
Create Date: 2025-07-10 00:11:19.440038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '754c21b10d05'
down_revision = '480c1f93edf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_image', schema=None) as batch_op:
        batch_op.create_index('idx_global_image_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('idx_global_image_user_date', ['user_id', 'upload_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_image', schema=None) as batch_op:
        batch_op.drop_index('idx_global_image_user_date')
        batch_op.drop_index('idx_global_image_entity')

    # ### end Alembic commands ###
