"""Add missing backtest configuration fields

Revision ID: 7ca2a38e51a9
Revises: 85a637d02d07
Create Date: 2025-08-01 21:29:15.962081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ca2a38e51a9'
down_revision = '85a637d02d07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backtest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initial_capital', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('primary_instrument', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('position_sizing', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('trade_management', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backtest', schema=None) as batch_op:
        batch_op.drop_column('trade_management')
        batch_op.drop_column('position_sizing')
        batch_op.drop_column('primary_instrument')
        batch_op.drop_column('initial_capital')

    # ### end Alembic commands ###
